In [2]:
%run 'import_dbase.ipynb'
%run 'import_pickle.ipynb'
dBase = 'rct005'
# this is the run you are interested in pickling
run = '004'
# add run to run list so we have a unified log file
runlist = ['002', '003', '004', '005']
cursor = connectDbase('rct05db')
picklePath = './Data/' + dBase + '/'

In [ ]:
pickleLogFile(cursor, dBase, runlist, picklePath, forceWrite=True)

In [3]:
log = pd.read_pickle(picklePath+dBase+'_log.pkl')
log

                    date state                     comment eventId  run
0    2015-12-12 04:30:00     1     start 000 low oscillate       1  000
1    2015-12-12 06:30:00     0       end 000 low oscillate       1  000
2    2015-12-12 12:45:00     1  start 000 medium oscillate       2  000
3    2015-12-12 14:45:00     0    end 000 medium oscillate       2  000
4    2015-12-13 12:00:00     1    start 000 high oscillate       3  000
5    2015-12-13 16:00:00     0      end 000 high oscillate       3  000
6    2015-12-22 04:00:00     1                   start 001       4  001
7    2015-12-22 08:00:00     0                     end 001       4  001
8    2015-12-18 15:00:00     1          start 002 P level1       5  002
9    2015-12-18 15:30:00     0            end 002 P level1       5  002
10   2015-12-18 19:15:00     1          start 002 P level2       6  002
11   2015-12-18 20:00:00     0            end 002 P level2       6  002
12   2015-12-18 23:15:00     1          start 002 P level3       7  002
13   2015-12-19 00:00:00     0            end 002 P level3       7  002
14   2015-12-19 03:15:00     1          start 002 P level4       8  002
15   2015-12-19 04:00:00     0            end 002 P level4       8  002
16   2015-12-19 07:15:00     1          start 002 P level5       9  002
17   2015-12-19 08:00:00     0            end 002 P level5       9  002
18   2015-12-19 11:15:00     1          start 002 P level6      10  002
19   2015-12-19 12:00:00     0            end 002 P level6      10  002
20   2015-12-19 15:15:00     1          start 002 P level7      11  002
21   2015-12-19 16:00:00     0            end 002 P level7      11  002
22   2015-12-19 19:15:00     1      start 002 P level Peak      12  002
23   2015-12-19 20:00:00     0        end 002 P level Peak      12  002
24   2015-12-19 23:15:00     1          start 002 P level1      13  002
25   2015-12-20 00:00:00     0            end 002 P level1      13  002
26   2015-12-20 03:15:00     1          start 002 P level2      14  002
27   2015-12-20 04:00:00     0            end 002 P level2      14  002
28   2015-12-20 07:15:00     1          start 002 P level3      15  002
29   2015-12-20 08:00:00     0            end 002 P level3      15  002
..                   ...   ...                         ...     ...  ...
240  2016-02-05 09:15:00     1         start 011 P 8 cycle     121  011
241  2016-02-05 09:45:00     0           end 011 P 8 cycle     121  011
242  2016-02-05 11:15:00     1         start 011 P 9 cycle     122  011
243  2016-02-05 15:00:00     0           end 011 P 9 cycle     122  011
244  2016-02-05 18:00:00     1        start 011 oscillate1     123  011
245  2016-02-06 10:00:00     0          end 011 oscillate1     123  011
246  2016-02-07 15:00:00     1        start 011 oscillate2     124  011
247  2016-02-08 12:00:00     0          end 011 oscillate2     124  011
248  2016-02-08 18:00:00     1        start 011 oscillate2     125  011
249  2016-02-09 06:00:00     0          end 011 oscillate2     125  011
250  2016-02-09 10:00:00     1        start 011 oscillate3     126  011
251  2016-02-09 12:00:00     0          end 011 oscillate3     126  011
252  2016-02-09 20:00:00     1        start 011 oscillate4     127  011
253  2016-02-11 08:00:00     0          end 011 oscillate4     127  011
254  2016-02-13 17:00:00     1   start 012 small oscillate     128  012
255  2016-02-16 10:00:00     0     end 012 small oscillate     128  012
256  2016-02-16 15:21:00     1     start 012 big oscillate     129  012
257  2016-02-17 11:21:00     0       end 012 big oscillate     129  012
258  2016-02-19 21:00:00     1         start 013 oscillate     130  013
259  2016-02-22 04:00:00     0           end 013 oscillate     130  013
260  2016-03-15 17:00:00     1     start 014 low oscillate     131  014
261  2016-03-15 18:00:00     0       end 014 low oscillate     131  014
262  2016-03-15 23:00:00     1    start 014 high oscillate     132  014
263  2016-03-16 10:00:00     0      end 014 high oscillate     132  014
264  2016-03-16 19:00:00     1         start 015 oscillate     133  015
265  2016-03-17 15:00:00     0           end 015 oscillate     133  015
266  2016-03-22 12:00:00     1    start 016 high oscillate     134  016
267  2016-03-24 12:00:00     0      end 016 high oscillate     134  016
268  2016-04-01 15:00:00     1     start 016 low oscillate     135  016
269  2016-04-03 15:00:00     0       end 016 low oscillate     135  016

[270 rows x 5 columns]

In [ ]:
pickleSensorFiles(cursor, dBase, '003', Path)

In [ ]:
# this is only if you want to make a paticular pickle file
for ii in [0]:
    pickleOneSensorFiles(cursor, dBase, run, ii, picklePath)

In [ ]:
# this if for pickling runs from different dbase - only works for RTD right now
dBase_alt = 'rct007b'
run = '003'
run_alt = '004'

pickleCrossDbaseSensorFiles(cursor, dBase, dBase_alt, run, run_alt, picklePath)

In [ ]:
## pickle entire run from the log file

In [8]:
def pickleEventFiles(dbase, run, logFile, tableList, outpath):
    cursor = connectDbase('rct05db')
    log = pd.read_pickle(logFile)
    log = log[log['run']==run]
            
    for eventId in log.eventId.unique():
        s = str(log[(log.eventId==eventId) & (log.state =='1')].date.values[0])    
        e = str(log[(log.eventId==eventId) & (log.state =='0')].date.values[0])    
        for tbName in tableList:
            
            filename = dbase + '_' + run + '_' + str(eventId) + '_' + tbName + '.pkl'
            print 'Pickling %s'%filename
            dfTable = readDateTable(cursor, tbName, s, e)             
            dfTable.to_pickle(outpath + '/' + filename)

In [9]:
dBase = 'rct005'
dbase = 'rct005'
run = '011'
outpath = '/home/ihs3/Documents/Notebooks/Data/archive/rct005/data/'
pickleEventFiles(dbase,run,picklePath+dBase+'_log.pkl',['011_data'],outpath)

Pickling rct005_011_110_011_data.pkl
Pickling rct005_011_111_011_data.pkl
Pickling rct005_011_112_011_data.pkl
Pickling rct005_011_113_011_data.pkl
Pickling rct005_011_114_011_data.pkl
Pickling rct005_011_115_011_data.pkl
Pickling rct005_011_116_011_data.pkl
Pickling rct005_011_117_011_data.pkl
Pickling rct005_011_118_011_data.pkl
Pickling rct005_011_119_011_data.pkl
Pickling rct005_011_120_011_data.pkl
Pickling rct005_011_121_011_data.pkl
Pickling rct005_011_122_011_data.pkl
Pickling rct005_011_123_011_data.pkl
Pickling rct005_011_124_011_data.pkl
Pickling rct005_011_125_011_data.pkl
Pickling rct005_011_126_011_data.pkl
Pickling rct005_011_127_011_data.pkl

In [ ]:
%ls Data/archive/rct005