In [25]:
%run 'import_dbase.ipynb'
%run 'import_pickle.ipynb'
dBase = 'rct007'
# this is the run you are interested in pickling
run = '004'
# add run to run list so we have a unified log file
runlist = ['002', '003', '004', '005']
cursor = connectDbase('rct007')
picklePath = './Data/' + dBase + '/'

In [26]:
pickleLogFile(cursor, dBase, runlist, picklePath, forceWrite=True)

make corrections

ProgrammingError: (1146, "Table 'rct007.005_logdata' doesn't exist")

In [27]:
log = pd.read_pickle(picklePath+dBase+'_log.pkl')
log

,date,state,comment,eventId,run
0,2016-06-28 00:46:39.381692,1,"Data collection START for Duty Cyce: 0, Gas: V...",0,004
1,2016-06-28 01:16:41.334500,0,"Data collection STOP for Duty Cyce: 0, Gas: Va...",0,004
2,2016-06-28 02:46:47.820485,1,"Data collection START for Duty Cyce: 0.05, Gas...",1,004
3,2016-06-28 03:16:49.830191,0,"Data collection STOP for Duty Cyce: 0.05, Gas:...",1,004
4,2016-06-28 04:46:56.306332,1,"Data collection START for Duty Cyce: 0.1, Gas:...",2,004
5,2016-06-28 05:16:58.364696,0,"Data collection STOP for Duty Cyce: 0.1, Gas: ...",2,004
6,2016-06-28 07:07:06.402626,1,"Data collection START for Duty Cyce: 0.2, Gas:...",3,004
7,2016-06-28 07:37:08.680572,0,"Data collection STOP for Duty Cyce: 0.2, Gas: ...",3,004
8,2016-06-28 09:17:15.895275,1,"Data collection START for Duty Cyce: 0.4, Gas:...",4,004
9,2016-06-28 09:47:17.810393,0,"Data collection STOP for Duty Cyce: 0.4, Gas: ...",4,004
10,2016-06-28 11:57:27.140698,1,"Data collection START for Duty Cyce: 0.6, Gas:...",5,004
11,2016-06-28 12:27:29.471676,0,"Data collection STOP for Duty Cyce: 0.6, Gas: ...",5,004
12,2016-06-28 15:07:41.222185,1,"Data collection START for Duty Cyce: 0, Gas: V...",6,004
13,2016-06-28 15:37:43.563907,0,"Data collection STOP for Duty Cyce: 0, Gas: Va...",6,004
14,2016-06-28 15:50:06.504234,1,"Data collection START for Duty Cyce: 0, Gas: V...",7,004
15,2016-06-28 16:20:08.797504,0,"Data collection STOP for Duty Cyce: 0, Gas: Va...",7,004
16,2016-06-28 17:50:15.421791,1,"Data collection START for Duty Cyce: 0.05, Gas...",8,004
17,2016-06-28 18:20:17.367728,0,"Data collection STOP for Duty Cyce: 0.05, Gas:...",8,004
18,2016-06-28 20:28:16.966737,1,"Data collection START for Duty Cyce: 0.1, Gas:...",9,004
19,2016-06-28 20:58:19.125531,0,"Data collection STOP for Duty Cyce: 0.1, Gas: ...",9,004
20,2016-06-28 22:48:27.302534,1,"Data collection START for Duty Cyce: 0.2, Gas:...",10,004
21,2016-06-28 23:18:29.733936,0,"Data collection STOP for Duty Cyce: 0.2, Gas: ...",10,004
22,2016-06-29 01:08:37.990877,1,"Data collection START for Duty Cyce: 0.4, Gas:...",11,004
23,2016-06-29 01:38:39.975542,0,"Data collection STOP for Duty Cyce: 0.4, Gas: ...",11,004
24,2016-06-29 03:48:49.371956,1,"Data collection START for Duty Cyce: 0.6, Gas:...",12,004
25,2016-06-29 04:18:51.585325,0,"Data collection STOP for Duty Cyce: 0.6, Gas: ...",12,004
26,2016-06-29 06:39:01.751238,1,"Data collection START for Duty Cyce: 0, Gas: V...",13,004
27,2016-06-29 07:09:03.929523,0,"Data collection STOP for Duty Cyce: 0, Gas: Va...",13,004
28,2016-06-29 14:34:36.100219,1,"Data collection START for Duty Cyce: 0, Gas: A...",14,004
29,2016-06-29 15:04:38.166214,0,"Data collection STOP for Duty Cyce: 0, Gas: Ar...",14,004
...,...,...,...,...,...
250,2016-07-22 04:27:54.340585,1,"Data collection START for Duty Cyce: 0, Gas: D...",125,004
251,2016-07-22 04:57:56.585091,0,"Data collection STOP for Duty Cyce: 0, Gas: De...",125,004
252,2016-07-22 18:17:51.437925,1,"Data collection START for Duty Cyce: 0, Gas: D...",126,004
253,2016-07-22 18:47:53.766417,0,"Data collection STOP for Duty Cyce: 0, Gas: De...",126,004
254,2016-07-22 20:18:00.177727,1,"Data collection START for Duty Cyce: 0.05, Gas...",127,004
255,2016-07-22 20:48:02.272427,0,"Data collection STOP for Duty Cyce: 0.05, Gas:...",127,004
256,2016-07-22 22:18:08.715823,1,"Data collection START for Duty Cyce: 0.1, Gas:...",128,004
257,2016-07-22 22:48:10.839833,0,"Data collection STOP for Duty Cyce: 0.1, Gas: ...",128,004
258,2016-07-23 00:38:18.928497,1,"Data collection START for Duty Cyce: 0.2, Gas:...",129,004
259,2016-07-23 01:08:21.097089,0,"Data collection STOP for Duty Cyce: 0.2, Gas: ...",129,004
260,2016-07-23 02:58:29.194177,1,"Data collection START for Duty Cyce: 0.4, Gas:...",130,004
261,2016-07-23 03:28:31.184770,0,"Data collection STOP for Duty Cyce: 0.4, Gas: ...",130,004
262,2016-07-23 05:58:42.084746,1,"Data collection START for Duty Cyce: 0.6, Gas:...",131,004
263,2016-07-23 06:28:44.176888,0,"Data collection STOP for Duty Cyce: 0.6, Gas: ...",131,004
264,2016-07-23 08:58:55.214170,1,"Data collection START for Duty Cyce: 0, Gas: D...",132,004
265,2016-07-23 09:28:57.534046,0,"Data collection STOP for Duty Cyce: 0, Gas: De...",132,004
266,2016-07-26 21:12:32.935434,1,"Data collection START for Duty Cyce: 0, Gas: H...",133,004
267,2016-07-26 21:42:35.168807,0,"Data collection STOP for Duty Cyce: 0, Gas: He...",133,004
268,2016-07-26 23:12:42.038858,1,"Data collection START for Duty Cyce: 0.05, Gas...",134,004
269,2016-07-26 23:42:44.214358,0,"Data collection STOP for Duty Cyce: 0.05, Gas:...",134,004
270,2016-07-27 01:12:51.037202,1,"Data collection START for Duty Cyce: 0.1, Gas:...",135,004
271,2016-07-27 01:42:53.190184,0,"Data collection STOP for Duty Cyce: 0.1, Gas: ...",135,004
272,2016-07-27 03:23:00.175777,1,"Data collection START for Duty Cyce: 0.2, Gas:...",136,004
273,2016-07-27 03:53:02.216298,0,"Data collection STOP for Duty Cyce: 0.2, Gas: ...",136,004
274,2016-07-27 05:43:09.944541,1,"Data collection START for Duty Cyce: 0.4, Gas:...",137,004
275,2016-07-27 06:13:12.267361,0,"Data collection STOP for Duty Cyce: 0.4, Gas: ...",137,004
276,2016-07-27 08:13:21.268337,1,"Data collection START for Duty Cyce: 0.6, Gas:...",138,004
277,2016-07-27 08:43:23.516961,0,"Data collection STOP for Duty Cyce: 0.6, Gas: ...",138,004
278,2016-07-27 11:13:34.629619,1,"Data collection START for Duty Cyce: 0, Gas: H...",139,004
279,2016-07-27 11:43:36.763892,0,"Data collection STOP for Duty Cyce: 0, Gas: He...",139,004

In [ ]:
pickleSensorFiles(cursor, dBase, '003', picklePath)

In [ ]:
# this is only if you want to make a paticular pickle file
for ii in [0]:
    pickleOneSensorFiles(cursor, dBase, run, ii, picklePath)

In [ ]:
# this if for pickling runs from different dbase - only works for RTD right now
dBase_alt = 'rct007b'
run = '003'
run_alt = '004'

pickleCrossDbaseSensorFiles(cursor, dBase, dBase_alt, run, run_alt, picklePath)

In [ ]:
## pickle entire run from the log file

In [3]:
def pickleEventFiles(dbase, run, logFile, tableList, outpath):
    cursor = connectDbase('rct05db')
    log = pd.read_pickle(logFile)
    log = log[log['run']==run]
            
    for eventId in log.eventId.unique():
        s = str(log[(log.eventId==eventId) & (log.state =='1')].date.values[0])    
        e = str(log[(log.eventId==eventId) & (log.state =='0')].date.values[0])    
        for tbName in tableList:
            
            filename = dbase + '_' + run + '_' + str(eventId) + '_' + tbName + '.pkl'
            print 'Pickling %s'%filename
            dfTable = readDateTable(cursor, tbName, s, e)             
            dfTable.to_pickle(outpath + '/' + filename)

In [ ]:
pickleEventFiles('rct005', '002','Data/rct005/rct005_log.pkl', ['002_highsamp'], 'Data/archive/rct005/data')

Pickling rct005_002_5_002_highsamp.pkl

In [ ]:
pickleEventFiles('rct005', '002','Data/rct005/rct005_log.pkl', ['002_lowsamp'], 'Data/archive/rct005/data')

In [ ]:
%ls Data/archive/rct005